// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlJG-LToe-Pz2lTJ5lFmnLynWcYP5-x-c',
    appId: '1:59835914200:web:45dc2b5c48da5e63c644ad',
    messagingSenderId: '59835914200',
    projectId: 'book-tok-2b9f4',
    authDomain: 'book-tok-2b9f4.firebaseapp.com',
    storageBucket: 'book-tok-2b9f4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvnUmELtRMLVJdTrSfkUsru6nM0b6Szgc',
    appId: '1:59835914200:android:da673db9d60c3434c644ad',
    messagingSenderId: '59835914200',
    projectId: 'book-tok-2b9f4',
    storageBucket: 'book-tok-2b9f4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqPeExB70iZnviDfOYozmxcghVrLskegI',
    appId: '1:59835914200:ios:e32ed6bf7933f1a4c644ad',
    messagingSenderId: '59835914200',
    projectId: 'book-tok-2b9f4',
    storageBucket: 'book-tok-2b9f4.firebasestorage.app',
    iosBundleId: 'com.example.bookTok',
  );
}
